### ISSUE TITLE
Error: Could not find unique group variables...

### ISSUE THREAD

**Issue by carlosyanez** [hafen/trelliscopejs#113]
Hi,

I've found the above error message when running the trelliscope() function.
Before posting a large reproducible example, am I missing something in my data frame that triggers the message (i.e. some particular variable type,etc)?

Thanks
Carlos

**Comment by carlosyanez** [comment]
I've reduced the number of entries in my data frame (it has +50k rows) and the function works again... It is there any official limit to the size of the input data frame?

**Comment by hafen** [comment]
Interesting. This isn't an issue with the size of the data. With your full larger data frame, when you do something like this:

```r
sapply(dat, anyDuplicated)
```

Do you have any columns that have a result of 0?

**Comment by carlosyanez** [comment]
No

**Comment by hafen** [comment]
This means all variables in the data frame have at least one duplicated value. For trelliscope to work, you need to have one variable that is unique.

**Comment by carlosyanez** [comment]
Thanks!. I'm cleaning the data and I'll give it another go!
