### ISSUE TITLE
add functionality for ggplotly() from plotly package

### ISSUE THREAD

**Issue by Emaasit** [hafen/trelliscopejs#12]
Tried wrapping a ggplot2 object developed with facet_trelliscope  like this:

```{r echo = FALSE}
library(trelliscopejs)
library(ggplot2)
library(plotly)
p <- qplot(cty, hwy, data = mpg) +
  geom_abline(alpha = 0.5) +
  xlim(7, 37) + ylim(9, 47) + theme_bw() +
  facet_trelliscope(~ manufacturer + class, nrow = 2, ncol = 4, self_contained = TRUE, path = "mydisplays")
ggplotly(p)
```

But there was NO difference, i.e no trelliscope effect in the output. (cc @cpsievert)

![newplot](https://cloud.githubusercontent.com/assets/7738216/20469173/b46074a0-af52-11e6-92cb-d391605269f6.png)

**Comment by hafen** [comment]
This won't work with ggpoltly in this way, at least not right now. `facet_trelliscope()` is designed to work with ggplot objects only. To make it work with ggplotly, you need to make each individual panel a ggplotly object with `trelliscope()`, in the same fashion as the rbokeh examples.

**Comment by hafen** [comment]
This functionality has been added. See here: http://ryanhafen.com/blog/trelliscopejs-plotly
