### ISSUE TITLE
Permission to use trelliscopejs hex logo in presentation

### ISSUE THREAD

**Issue by JauntyJJS** [hafen/trelliscopejs#120]
Hi,

Just to say that I will be presenting the use of trelliscopejs on the upcoming R Medicine conference.

Here is the link of what has been done so far.
https://jauntyjjs.github.io/RMedicine2022

I wanted to ask if I can use the trelliscopejs logo on slide 10. Thank you.

**Comment by hafen** [comment]
Thanks for sharing the talk and yes please feel free to use the logo!

Also note there have been several features added that haven't really been documented but we will hopefully be rolling out more documentation and examples soon.

**Comment by JauntyJJS** [comment]
Noted with thanks.
