### ISSUE TITLE
Change by_row depency to purrrlyr from purrr

### ISSUE THREAD

**Issue by abresler** [hafen/trelliscopejs#38]

**Comment by hafen** [comment]
Thanks! I'm merging a PR to this effect right now.

**Comment by vikram-rawat** [comment]
library(trelliscopejs)
library(ggplot2)
library(gapminder)
library(tidyverse)
qplot(year, lifeExp, data = gapminder) +
    xlim(1948, 2011) + ylim(10, 95) + theme_bw() +
    facet_trelliscope(~ country + continent, nrow = 2, ncol = 7, width = 300)

This example doesn't work at all it gives me this error...

===================================
using data from the first layer
Error: 'as_mapper' is not an exported object from 'namespace:purrr'
===================================

what should I do

**Comment by hafen** [comment]
I'm not able to reproduce this. You may have an outdated version. Can you reinstall trelliscopejs and if the issue persists please provide more info (`sessionInfo()`, etc.).
