### ISSUE TITLE
facet_trelliscope error: 'could not find function "scale_fn"' when no axis limits set

### ISSUE THREAD

**Issue by luke-a** [hafen/trelliscopejs#48]
While it worked with ggplot2 2.2.1 (on CRAN), `facet_trelliscope` fails with the latest development versions of ggplot & its friends. Here's an example [from Stackoverflow.com](https://stackoverflow.com/questions/45596031/using-facet-trelliscope-without-defining-axis-limits): 

```
# devtools::install_github("tidyverse/ggplot2")
library(trelliscopejs)
packageVersion("trelliscopejs")
# [1] ‘0.1.9’
library(ggplot2)
packageVersion("ggplot2")
# [1] ‘2.2.1.9000’
x <- 1:10
y <- 1:10
group <- rep(c("A","B"),5)
df <- data.frame(group, x, y)

# Works:
ggplot(df, aes(x, y)) + geom_point() + 
  xlim(0, 10) + ylim(0, 10) + # <----------
  facet_trelliscope(~group)

# FAILS:
ggplot(df, aes(x, y)) + geom_point() + 
  facet_trelliscope(~group)
# Error in scale_fn() : could not find function "scale_fn"
```
It might work to explicitly set the limits on continous scales. However, I would not know how to do it for discrete scales...

**Comment by hafen** [comment]
Interesting - thanks for the report. Things must be represented internally a bit differently in the development version. I'll look into it. Also ping @schloerke.

**Comment by hathawayj** [comment]
@schloerke did you get this resolved.  I still see the same issue.

**Comment by schloerke** [comment]
Thanks @hathawayj for the reminder.  (Passed my defense!)

Fixed.  They changed the scale locations.  Boo. 

```r
devtools::install_github("hafen/trelliscopejs#53")
```

**Comment by schloerke** [comment]
Waiting for travis, then I'll merge into master

**Comment by schloerke** [comment]
```r
devtools::install_github("hafen/trelliscopejs")
```

**Comment by hathawayj** [comment]
@schloerke thanks.
