### ISSUE TITLE
trelliscope() not creating index.html

### ISSUE THREAD

**Issue by rensa** [hafen/trelliscopejs#70]
I'm not quite sure how to create a reprex for this, but my trelliscope installation has essentially stopped creating the `index.html` whenever I try to build a trelliscope. Everything in the `appfiles` folder is there, but there's no `index.html`, so I can't open the trelliscope. I've tried shifting the `path` to an empty directory, and I've tried reinstalling the package, but I'm not too sure what to do now.

**Comment by statisticiansix** [comment]
Hello,

I had the same issue and I think I have found the solution. By any chance are you assigning your dashboards to a variable? It would appear that if you do the index.html file isn't created

```{r}
d <- mpg %>%
  group_by(manufacturer, class) %>%
  summarise(
    panel = panel(
      figure(xlab = "City mpg", ylab = "Highway mpg") %>%
        ly_points(cty, hwy)))

d %>% trelliscope(name = "city_vs_highway_mpg",path='Index Contained')
noIndex <- d %>% trelliscope(name = "city_vs_highway_mpg",path='No Index Contained')

```
Hopefully this solves your issue.

Best
Six

**Comment by rensa** [comment]
Yup, that's it. /facepalm Thanks, @statisticiansix!
