### ISSUE TITLE
The use of the folder button

### ISSUE THREAD

**Issue by JauntyJJS** [hafen/trelliscopejs#84]
Hi,

I apologize in advanced for asking a naive question 

In the webpage,
https://cran.r-project.org/web/packages/autocogs/readme/README.html

There is this blue folder created beside the exclamation help button.

![image](https://user-images.githubusercontent.com/9066508/65018122-eee85b80-d95a-11e9-93de-c00fae1ade81.png)

May I ask what is that and how do I create this folder in this R package ?

Thank you for the clarification

**Comment by hafen** [comment]
The folder button is activated when you have more than one display in a directory. If you create more than one display with the same `path` argument, but with different `name`s, the icon will appear and you will be able to switch between the different displays.

**Comment by JauntyJJS** [comment]
Thank you for the help. I manage to get the folder to appear when I key in the following code

```
library(ggplot2)
library(dplyr)
library(tidyr)
library(gapminder)
library(plotly)
library(trelliscopejs)

scatter <- function(d){
  
  p <- plot_ly(data = d , x = ~lifeExp, y = ~year, type = 'scatter',mode ="markers")
  return(p)
  
}

gapminder %>%
  group_by(country, continent) %>%
  nest() %>%
  mutate(panel = map_plot(data,scatter)) %>%
  trelliscope(name = "gapminder_lifeexp",path="./out", nrow = 2, ncol = 6, self_contained = FALSE)

gapminder %>%
  group_by(country, continent) %>%
  nest() %>%
  mutate(panel = map_plot(data,scatter)) %>%
  trelliscope(name = "gapminder_lifeexp2",path="./out", nrow = 2, ncol = 6, self_contained = FALSE)

```
![image](https://user-images.githubusercontent.com/9066508/65255854-31fc2780-db31-11e9-8087-6ea241b59a16.png)

However, when I set `self_contained = TRUE`, instead

![image](https://user-images.githubusercontent.com/9066508/65255902-44766100-db31-11e9-9b3b-c6e37b8bf911.png)

Clicking on the black button gives me a blank screen instead

![image](https://user-images.githubusercontent.com/9066508/65255963-5952f480-db31-11e9-9597-c46f2e8dfcad.png)

Not sure if this is a known issue already.

**Comment by hafen** [comment]
`self_contained = TRUE` is meant only for a single display. Multiple displays only work when stored in a directory, which inherently makes them not self-contained. This probably isn't documented well enough, and I should probably add something that warns you about self-contained when specifying a path that already contains other displays.
