### ISSUE TITLE
package or namespace load failed for ‘trelliscopejs’

### ISSUE THREAD

**Issue by yanqingfu** [hafen/trelliscopejs#97]
R 4.0.2 when load the trelliscopejs package
the following error shows:

library(trelliscopejs)
Error: package or namespace load failed for ‘trelliscopejs’:
 .onLoad failed in loadNamespace() for 'checkmate', details:
  call: NULL
  error: package ‘backports’ does not have a namespace

I tried to remove the package and reinstall, the problem still exists.

**Comment by hafen** [comment]
I'm not sure what the issue could be. How did you install the package? I'm assuming it is some system-specific issue since I haven't seen any other reports of this nature.

**Comment by yanqingfu** [comment]
problem solved
